added prettier and updated husky and lint config to work with prettier
paketacredito/Academy pull request #8
Opened 2020-11-27 19:46 UTC by talesperes

Adicionado prettier ao projeto para realizar a formatação do código no pré push utilizando o husky, e alterado algumas rules do ESLint para aceitar a formatação do prettier.

2020-11-27 19:50 UTC, rafaelrvcn approved these changes

2020-11-27 20:01 UTC, igorarmelin approved these changes

2020-11-27 20:08 UTC, Tautorn requested changes

2020-11-27 20:08 UTC, Tautorn commented on package.json
> +    "pretty": "prettier --write --tab-width 2 --use-tabs --arrow-parens avoid --single-quote --quote-props preserve --trailing-comma none ."
Poderia colocar em um arquivo separado?

Exemplo:

// .prettierrc.js
```
module.exports = {
  bracketSpacing: true,
  jsxBracketSameLine: false,
  singleQuote: true,
  trailingComma: "none",
  semi: false,
  arrowParens: "always",
  printWidth: 90
};
```

2020-11-27 20:52 UTC, igorarmelin approved these changes

2020-11-27 20:52 UTC, rafaelrvcn approved these changes

2020-11-30 13:27 UTC, Tautorn approved these changes

2020-11-30 13:29 UTC, rafaelrvcn approved these changes

2020-11-30 13:31 UTC, igorarmelin approved these changes

2020-11-30 13:31 UTC, merged